#!/bin/bash
# Launch a PIU legacy game version via pumptools.
# Usage: piu-launch.sh <version-dir>
#   version-dir: path to directory named XX_Name (e.g. /mnt/piu/07_Extra)
#                Must contain XX_Name.img.gz alongside if not yet extracted.
#
# Hook mapping: each version dir may contain a .pumptools/hook-name file
# specifying which pumptools hook to use. Defaults listed in HOOK_MAP below.
#
# IO mode: controlled by .pumptools/hook.conf. Default: keyboard (QEMU-safe).
# On real hardware with PIUIO present, override InputImpl in hook.conf.

set -euo pipefail

PUMPTOOLS=/opt/pumptools
PIUIO2KEY_SVC=piuio2key.service

VERSION_DIR="${1:-}"
[[ -n "$VERSION_DIR" ]] || { echo "Usage: $0 <version-dir>" >&2; exit 1; }
[[ -d "$VERSION_DIR" || -f "${VERSION_DIR}.img.gz" ]] || {
    echo "ERROR: $VERSION_DIR not found" >&2; exit 1
}

VERSION_NAME="$(basename "$VERSION_DIR")"
IMG_GZ="$(dirname "$VERSION_DIR")/${VERSION_NAME}.img.gz"
PT_DIR="${VERSION_DIR}/.pumptools"
GAME_DIR="${VERSION_DIR}/game"

# ---------------------------------------------------------------------------
# Hook selection — map version name prefix to pumptools hook binary/dir
# ---------------------------------------------------------------------------
declare -A HOOK_MAP=(
    ["07"]="exchook"     # PIU Extra / Exceed series
    ["08"]="exchook"
    ["09"]="exchook"
    ["10"]="exchook"
    ["11"]="mk3hook"     # Premiere 2 (MK3 Linux port)
    ["12"]="mk3hook"
    ["13"]="mk3hook"
    ["20"]="nxhook"      # NX
    ["21"]="nxahook"     # NX Absolute
    ["22"]="nx2hook"     # NX2
    ["23"]="prohook"     # Pro
    ["24"]="pro2hook"    # Pro 2
    ["25"]="fexhook"     # Fiesta EX
    ["26"]="primehook"   # Prime (v122)
)

PREFIX="${VERSION_NAME:0:2}"
HOOK_NAME="${HOOK_MAP[$PREFIX]:-}"

# Allow override via .pumptools/hook-name file
if [[ -f "${PT_DIR}/hook-name" ]]; then
    HOOK_NAME="$(cat "${PT_DIR}/hook-name")"
fi

[[ -n "$HOOK_NAME" ]] || {
    echo "ERROR: no hook mapping for version prefix '$PREFIX' in $VERSION_NAME" >&2
    echo "       Create ${PT_DIR}/hook-name with the hook name (e.g. fexhook)" >&2
    exit 1
}

HOOK_BIN="${PUMPTOOLS}/${HOOK_NAME}"
[[ -f "$HOOK_BIN" || -d "$HOOK_BIN" ]] || {
    echo "ERROR: pumptools hook not found: $HOOK_BIN" >&2
    echo "       Is pumptools installed at $PUMPTOOLS?" >&2
    exit 1
}

# ---------------------------------------------------------------------------
# Extract game tree from .img.gz on first run
# ---------------------------------------------------------------------------
if [[ ! -d "$GAME_DIR" ]]; then
    [[ -f "$IMG_GZ" ]] || {
        echo "ERROR: no extracted game dir and no .img.gz: $IMG_GZ" >&2; exit 1
    }

    echo "==> First run: extracting $VERSION_NAME from disk image..."
    echo "    This takes a few minutes. Subsequent launches are instant."

    LOOP_DEV=""
    MOUNT_PT="$(mktemp -d)"
    cleanup_extract() {
        set +e
        [[ -n "$LOOP_DEV" ]] && umount "$MOUNT_PT" 2>/dev/null
        [[ -n "$LOOP_DEV" ]] && losetup -d "$LOOP_DEV" 2>/dev/null
        rmdir "$MOUNT_PT" 2>/dev/null
    }
    trap cleanup_extract EXIT

    # Decompress to temp image, loop-mount with partition scanning.
    TMP_IMG="$(mktemp --suffix=.img)"
    echo "    Decompressing $IMG_GZ → $TMP_IMG"
    zcat "$IMG_GZ" > "$TMP_IMG"

    LOOP_DEV="$(losetup --find --partscan --show "$TMP_IMG")"
    echo "    Loop device: $LOOP_DEV"

    # Find first Linux partition (type 83).
    GAME_PART=""
    for part in "${LOOP_DEV}p"*; do
        [[ -b "$part" ]] || continue
        TYPE="$(blkid -o value -s TYPE "$part" 2>/dev/null || true)"
        [[ "$TYPE" == ext2 || "$TYPE" == ext3 || "$TYPE" == ext4 ]] && {
            GAME_PART="$part"; break
        }
    done
    [[ -n "$GAME_PART" ]] || {
        echo "ERROR: no ext2/3/4 partition found in $IMG_GZ" >&2; exit 1
    }

    echo "    Mounting $GAME_PART → $MOUNT_PT"
    mount -o ro "$GAME_PART" "$MOUNT_PT"

    mkdir -p "$GAME_DIR"
    echo "    Copying game tree → $GAME_DIR"
    rsync -a --info=progress2 "${MOUNT_PT}/" "${GAME_DIR}/"

    umount "$MOUNT_PT"
    losetup -d "$LOOP_DEV"; LOOP_DEV=""
    rm -f "$TMP_IMG"
    rmdir "$MOUNT_PT"
    trap - EXIT
    echo "    Extraction complete."
fi

# ---------------------------------------------------------------------------
# Set up pumptools working directory (.pumptools/)
# ---------------------------------------------------------------------------
mkdir -p "$PT_DIR"

# Write default hook.conf if absent. Keyboard IO for QEMU-safe testing.
# On real hardware, change InputImpl to piuio (hardware) or joystick.
if [[ ! -f "${PT_DIR}/hook.conf" ]]; then
    cat > "${PT_DIR}/hook.conf" <<'HOOKCONF'
# pumptools hook configuration — generated by piu-launch.sh
# IO mode: keyboard = X11 keyboard input (QEMU testing, no PIUIO required)
#          piuio    = real PIUIO/LXIO hardware
#          joystick = Linux joystick API (gamepad)
io = {
    # Options: keyboard, piuio, joystick
    piuio = {
        impl = "keyboard"
    }
}
patch = {
    hook = {
        # Intercept keyboard input in the game's main loop.
        main_loop = {
            x11_input_handler = true
        }
    }
}
HOOKCONF
    echo "    Created default hook.conf (keyboard IO mode)"
fi

# Symlink hook binary next to game dir so pumptools finds it.
HOOK_LINK="${VERSION_DIR}/hook"
[[ -e "$HOOK_LINK" ]] || ln -s "$HOOK_BIN" "$HOOK_LINK"

# ---------------------------------------------------------------------------
# Stop PIUIO2Key-Linux — pumptools owns IO from here
# ---------------------------------------------------------------------------
if systemctl is-active --quiet "$PIUIO2KEY_SVC" 2>/dev/null; then
    echo "==> Stopping $PIUIO2KEY_SVC (pumptools takes IO ownership)"
    systemctl stop "$PIUIO2KEY_SVC"
    PIUIO2KEY_WAS_RUNNING=1
else
    PIUIO2KEY_WAS_RUNNING=0
fi

restart_piuio2key() {
    if [[ "$PIUIO2KEY_WAS_RUNNING" -eq 1 ]]; then
        echo "==> Restarting $PIUIO2KEY_SVC"
        systemctl start "$PIUIO2KEY_SVC" || true
    fi
}
trap restart_piuio2key EXIT

# ---------------------------------------------------------------------------
# Launch game via pumptools
# ---------------------------------------------------------------------------
echo "==> Launching $VERSION_NAME via pumptools ($HOOK_NAME)"
cd "$VERSION_DIR"
exec "${HOOK_LINK}/hook" \
    --game-data-dir "$GAME_DIR" \
    --hook-config-file "${PT_DIR}/hook.conf"
